// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `factories` table.
    ///
    /// (Automatically generated by Diesel.)
    factories (id) {
        /// The `id` column of the `factories` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `name` column of the `factories` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Varchar,
        /// The `address` column of the `factories` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        address -> Varchar,
        /// The `fee` column of the `factories` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        fee -> Int4,
        /// The `version` column of the `factories` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        version -> Varchar,
    }
}

diesel::table! {
    /// Representation of the `pairs` table.
    ///
    /// (Automatically generated by Diesel.)
    pairs (id) {
        /// The `id` column of the `pairs` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `address` column of the `pairs` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        address -> Varchar,
        /// The `token0_id` column of the `pairs` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        token0_id -> Int4,
        /// The `token1_id` column of the `pairs` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        token1_id -> Int4,
        /// The `factory_id` column of the `pairs` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        factory_id -> Int4,
    }
}

diesel::table! {
    /// Representation of the `tokens` table.
    ///
    /// (Automatically generated by Diesel.)
    tokens (id) {
        /// The `id` column of the `tokens` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `address` column of the `tokens` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        address -> Varchar,
        /// The `symbol` column of the `tokens` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        symbol -> Nullable<Varchar>,
        /// The `name` column of the `tokens` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Nullable<Varchar>,
        /// The `decimals` column of the `tokens` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        decimals -> Int4,
    }
}

diesel::joinable!(pairs -> factories (factory_id));

diesel::allow_tables_to_appear_in_same_query!(
    factories,
    pairs,
    tokens,
);
